name: Emulate and Test OS

on: [push, pull_request]

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies for QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build pkg-config libglib2.0-dev libpixman-1-dev tree python3

    - name: Clone QEMU Source
      run: git clone https://gitlab.com/qemu-project/qemu.git

    - name: Build QEMU
      run: |
        cd qemu
        ./configure --target-list=aarch64-softmmu
        make -j$(nproc)

    - name: Install ARM GNU compiler
      run: |
        wget https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf.tar.xz
        tar xvJf arm-gnu-toolchain-13.3.rel1-x86_64-aarch64-none-elf.tar.xz

    - name: Run OS in QEMU
      run: |
        tree
        python3 -m venv Oxaminer/.venv
        ./Oxaminer/.venv/bin/pip install pyyaml
        ./Oxaminer/.venv/bin/python3 ./Oxaminer/main.py
