name: Makefile CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies for QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build pkg-config libglib2.0-dev libpixman-1-dev

    - name: Clone QEMU Source
      run: git clone https://gitlab.com/qemu-project/qemu.git

    - name: Build QEMU
      run: |
        cd qemu
        ./configure --target-list=aarch64-softmmu
        make -j$(nproc)

    - name: Run OS in QEMU
      run: |
        ./qemu/aarch64-softmmu/qemu-system-aarch64 \
          -M raspi4 \
          -kernel kernel8.img \
          -nographic
