name: Emulate and Test OS

on: [push, pull_request]

jobs:
  Run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Dependencies for QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build pkg-config libglib2.0-dev libpixman-1-dev tree

    - name: Clone QEMU Source
      run: git clone https://gitlab.com/qemu-project/qemu.git

    - name: Build QEMU
      run: |
        cd qemu
        ./configure --target-list=aarch64-softmmu
        make -j$(nproc)

    - name: Run OS in QEMU
      run: |
        ./Oxaminer/.venv/bin/python3 ./Oxaminer/main.py
